### ISSUE TITLE
Cloud manager build failing at "Build Images" step

### ISSUE THREAD

**Issue by kapil-gahlawat** [brightcove/Adobe-AEM-Brightcove-Connector#56]
Hi,

We used the 6.0 version zip provided here: https://github.com/brightcove/Adobe-AEM-Brightcove-Connector/releases/tag/6.0.0-cloud

Cloud manager build is failing at "Build Images" step with following error:

```
[91mjava.lang.IllegalStateException: Error while assembling launcher: Package has unresolved dependencies: com.coresecure:brightcove.all:[6.0.0-cp2fm-converted,6.0.0-cp2fm-converted]
[0m[91m	at org.apache.sling.feature.launcher.impl.Bootstrap.runWithException(Bootstrap.java:169)[0m[91m
[0m[91m	at com.adobe.granite.fact.command.PrepareContentCommand.doCall(PrepareContentCommand.java:174)[0m[91m
[0m[91m	at com.adobe.granite.fact.command.AbstractRepoCommand.call(AbstractRepoCommand.java:67)[0m[91m
[0m[91m	at com.adobe.granite.fact.command.buildimage.BuildImageTasks.doPrepareContent(BuildImageTasks.java:707)[0m[91m
[0m[91m	at com.adobe.granite.fact.command.buildimage.BuildImageExecutor.lambda$submit$1(BuildImageExecutor.java:110)
	at java.base/java.lang.Thread.run(Thread.java:834)
[0m[91mCaused by: shaded.org.apache.jackrabbit.vault.packaging.DependencyException: Package has unresolved dependencies: com.coresecure:brightcove.all:[6.0.0-cp2fm-converted,6.0.0-cp2fm-converted][0m[91m
[0m[91m	at shaded.org.apache.jackrabbit.vault.packaging.registry.impl.ExecutionPlanBuilderImpl.resolveInstall(ExecutionPlanBuilderImpl.java:257)[0m[91m
[0m[91m	at shaded.org.apache.jackrabbit.vault.packaging.registry.impl.ExecutionPlanBuilderImpl.validate(ExecutionPlanBuilderImpl.java:239)[0m[91m
[0m[91m	at org.apache.sling.feature.extension.content.ContentHandler.buildExecutionPlan(ContentHandler.java:87)
	at org.apache.sling.feature.extension.content.ContentHandler.handle(ContentHandler.java:127)
[0m[91m	at org.apache.sling.feature.launcher.impl.FeatureProcessor.prepareLauncher(FeatureProcessor.java:205)
	at org.apache.sling.feature.launcher.impl.Bootstrap.runWithException(Bootstrap.java:157)
	... 5 more

```

**Comment by kapil-gahlawat** [comment]
Hi,
This issue has been resolved now. We had to make some changes in your code and rebuild a new package. It was Cloud manager specific issue.

The issue was that we were installing the Brightcove package only in the author instance using install.author folder embedding. But Brightcove itself contains other modules like core, apps etc which are using the install folder. Cloud manager was ignoring this hierarchy. It was trying to install Brightcove in author but its submodules in publish as well. So, there was some inconsistency and the build was failing. We had to make changes to module embedding and used install.author for submodels as well. We recompiled your code and deployed and it worked.
