### ISSUE TITLE
Upgrade to AEM 6.5.21.0 is breaking connector

### ISSUE THREAD

**Issue by stiegjo** [brightcove/Adobe-AEM-Brightcove-Connector#70]
We just upgraded to AEM 6.5.21.0 and we're using brightcove_connector.ui.apps-6.0.6. When we try to load the Brightcove UI, we get the following error in the log:

`2024-08-01 11:57:35.803 ERROR [com.coresecure.brightcove.wrapper.webservices.BrcApi] org.apache.sling.commons.json.JSONException
org.apache.sling.commons.json.JSONException: A JSONObject text must begin with '{' at character 0 of 
	at org.apache.sling.commons.json.JSONTokener.syntaxError(JSONTokener.java:449) [org.apache.sling.commons.json:2.0.20]
	at org.apache.sling.commons.json.JSONObject.<init>(JSONObject.java:187) [org.apache.sling.commons.json:2.0.20]
	at org.apache.sling.commons.json.JSONObject.<init>(JSONObject.java:285) [org.apache.sling.commons.json:2.0.20]
	at com.coresecure.brightcove.wrapper.webservices.BrcApi.getLabels(BrcApi.java:227)
	at com.coresecure.brightcove.wrapper.webservices.BrcApi.apiLogic(BrcApi.java:682)
	at com.coresecure.brightcove.wrapper.webservices.BrcApi.executeRequest(BrcApi.java:716)
	at com.coresecure.brightcove.wrapper.webservices.BrcApi.doGet(BrcApi.java:97)
	at org.apache.sling.api.servlets.SlingSafeMethodsServlet.mayService(SlingSafeMethodsServlet.java:266) [org.apache.sling.api:2.27.2]
	at org.apache.sling.api.servlets.SlingAllMethodsServlet.mayService(SlingAllMethodsServlet.java:137) [org.apache.sling.api:2.27.2]
	at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:342) [org.apache.sling.api:2.27.2]
	at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:374) [org.apache.sling.api:2.27.2]
	at org.apache.sling.engine.impl.request.RequestData.service(RequestData.java:545) [org.apache.sling.engine:2.15.10]
	at org.apache.sling.engine.impl.filter.SlingComponentFilterChain.render(SlingComponentFilterChain.java:45) [org.apache.sling.engine:2.15.10]
	at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:88) [org.apache.sling.engine:2.15.10]
	at com.day.cq.wcm.core.impl.WCMDebugFilter.doFilter(WCMDebugFilter.java:156) [com.day.cq.wcm.cq-wcm-core:5.12.260]`

**Comment by stiegjo** [comment]
Issue was resolved - it was a. permission issue.
